version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '8000:8000'
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
  redis:
    image: redis:7-alpine
  db:
    image: postgres:15-alpine
